"""
Project 65: Voice Cloning Test Inference Script
"""

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from project65_voice_clone.dataset import get_reference_speakers
from project65_voice_clone.model import voice_cloner

def main():
    print("=== Testing Project 65: Voice Cloning Mini Studio ===")
    speakers = get_reference_speakers()
    if not speakers:
        print("No reference speakers found.")
        return

    speaker = speakers[0]
    print(f"Reference Speaker: {speaker['name']} ({speaker['path']})")

    target_text = "This is a custom cloned voice test generated by our deep learning pipeline."
    print(f"Target Text to Clone: \"{target_text}\"")

    res = voice_cloner.clone_voice(speaker["path"], target_text, output_filename="test_cloned.wav")
    print(f"\nCloned Audio File: {res['cloned_audio_path']}")
    print(f"Vocal Similarity Score: {res['similarity_score']}")
    print(f"Reference Gender: {res['reference_speaker']['gender']}")
    print(f"Mean Pitch: {res['reference_speaker']['mean_pitch_hz']} Hz")
    print(f"Spectral Centroid: {res['reference_speaker']['spectral_centroid_hz']} Hz")
    print(f"Processing Time: {res['processing_time_sec']}s")

    print("\n[OK] Project 65 Voice Cloning completed successfully.")
    print("===================================================\n")

if __name__ == "__main__":
    main()
